### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by AItechnology** [icodingc/ImageRetrieval-tf#1]
请问是否方便提供一下数据集和其他不方便上传的文件呢？由于是新手，所以希望先用原始的数据集跑一遍程序，方便学习和改进。非常感谢！

**Comment by icodingc** [comment]
因为我并没有训练网络，而是直接拿inceptino_v3训练好的模型，所以数据集你可以随便选取，只需要去抽特征就行了.也没必要用服装数据集，可以使用像oxford building5k,或者paris6k等公开的检索数据集。

**Comment by icodingc** [comment]
[Inception_v3](https://github.com/icodingc/image-retrieval-demo/tree/master/extract_feature/model-v3)是别人train好的。因为基本项目是依据[Inception](https://github.com/tensorflow/models/tree/master/inception)因此你可能需要先看懂这个代码。

**Comment by AItechnology** [comment]
好的，非常感谢，实在不懂我再问你吧！

**Comment by AItechnology** [comment]
inception倒是都懂，只不过刚开始入手检索相关的东西
