### ISSUE TITLE
关于没有类别标签，如何设置输出节点数

### ISSUE THREAD

**Issue by loo617** [icodingc/ImageRetrieval-tf#3]
你好，我是小白最近也在研究图像检索方面，如果说有100万张单样本图片，也就是没有类别标签的那种，如何设置输出节点数难道是100万吗？

**Comment by icodingc** [comment]
不是特别明白你说的输出结点是什么意思，分类类别个数？按照你说的如果数据没有标签，那就没办法训练网络呀，至少说分类任务不行。

**Comment by loo617** [comment]
我想通了，卷积神经网络只是一种监督算法，所以样本必须带有类别标签才能训练，可是像百度的以图搜图，难道训练集都是带类别标签的吗？

**Comment by icodingc** [comment]
并不了解百度是怎么作以图搜图的，不过训练的时候肯定是有一部分是带标签数据的。还没见过完全无标注数据去作检索。
