### ISSUE TITLE
重新训练问题

### ISSUE THREAD

**Issue by yunhai0920** [icodingc/ImageRetrieval-tf#4]
你好 请教一下看你的提取特征是直接用imagenet在inceptionV3上做分类训练得到的模型来提取特征的。这里有个问题想请教一下：
1.做图像搜索的话，如果是拿自己的数据集进行分类训练那么应该分多少类才合适呢，如果数据集不大，人工分类一下几十上百类还是可以接受的，但 比如我得数据集非常大的，细分类别可能会达到几千上万类别 这样呢？
2.做图像搜索是将之前训练的数据库提取特征打包成数据库后，然后对上传的图片也进行提取特征从数据库中找到最相似的图像， 这里数据库肯定是不断增加的 ，那么对于之前的模型是不是过段时间就要重新训练呢（比如新增加了一倍的新图像）

**Comment by icodingc** [comment]
1. 按理说类别越精细效果越好，几千上万类也不算大。人脸识别里超过百万的都有，只要你计算资源足够。
2. 模型迭代的问题。 这个要具体分析。 但是特征一定要保证是一个模型出来的这样才能够去做检索。

**Comment by yunhai0920** [comment]
@icodingc  非常感谢解答
之前一直在想对于提取特征来说 大牛们已经利用分类网络训练非常好的权重了。那么我直接拿他们的训练好的模型 直接去提取特征不也是可以的 反正不同物体提取的特征肯定不一样 然后直接拿这些特征做搜索不就可以了  现在想想 像淘宝 京东那些以图搜图的 应该是拿全网的图片分类后训练的吧（类别可能真的是千万亿级别的类别， 不敢想想 怎么去做的分类）

**Comment by icodingc** [comment]
那种级别的话，我也不太清楚。感觉不是纯分类能解决的。
